// ClientApp/src/pages/Login/PromsLogin/components/LoginError.tsx
import { Button } from "src/components/atoms/Button/Button";

interface IProps {
  onBack: () => void;
}

export const LoginError: React.FC<IProps> = (props): JSX.Element => {

  return (
    <>
      <h3 className="mb-3">
        Sorry, something went wrong.
      </h3>

      <div className="mb-3">
        Unfortunately we couldn't log you in this time. Please try again later.
      </div>

      <div className="mb-5">
        If the problem persists, please contact The Christie.
      </div>

      <div>
        <Button label="Back to login page" fullWidth onClick={props.onBack} />
      </div>
    </>
  );
}

// ClientApp-angular/src/app/pages/login/components/login-error/login-error.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-login-error',
  templateUrl: './login-error.component.html',
  styleUrls: ['./login-error.component.scss']
})
export class LoginErrorComponent implements OnInit {

  constructor() { }

  @Output() back: EventEmitter<any> = new EventEmitter();

  ngOnInit(): void {
  }

  onBack(): void {
    this.back.emit();
  }
}

<h3>Sorry, something went wrong.</h3>

<div class="text">
  Unfortunately we couldn't log you in this time. Please try again later.
</div>

<div class="text">
  If the problem persists, please contact The Christie.
</div>

<div>
  <button class="btn btn-primary w-100" (click)="onBack()">
    Back to login page
  </button>
</div>
