// ClientApp-angular/src/app/pages/login/components/nhs-number/nhs-number.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-nhs-number',
  templateUrl: './nhs-number.component.html',
  styleUrls: ['./nhs-number.component.scss']
})
export class NhsNumberComponent implements OnInit {

  constructor() { }

  @Input() disable: boolean = false;

  @Output() submit: EventEmitter<string> = new EventEmitter();
  @Output() tryAgain: EventEmitter<any> = new EventEmitter();

  nhsNumber: string = '';

  ngOnInit(): void {
  }

  onSubmit() {
    this.submit.emit(this.nhsNumber);
  }
}

<div class="text mb-2">
  To complete the login process please enter your NHS number.
</div>

<div class="text mb-4">
  You can find this on letters you've received from The Christie.
</div>

<h5 class="limit-width mb-2">Please enter your NHS number:</h5>

<div class="limit-width mb-3">
  <input type="text" class="form-control" [(ngModel)]="nhsNumber" [disabled]="disable">
</div>

<div class="limit-width mb-5">
  <button class="btn btn-primary w-100" [disabled]="!nhsNumber || disable" (click)="onSubmit()">
    Submit
  </button>
</div>

// ClientApp/src/pages/Login/PromsLogin/components/NhsNumber.tsx
import React from "react";
import { Button } from "src/components/atoms/Button/Button";
import { Input } from "src/components/atoms/Input";

interface IProps {
  disable?: boolean;
  onSubmit: (nhsNumber: string) => void;
}

export const NhsNumber: React.FC<IProps> = (props): JSX.Element => {
  const [nhs, setNhs] = React.useState<string>();

  return (
    <>
      <div className="mb-2">
        To complete the login process please enter your NHS number.
      </div>

      <div className="mb-4">
        You can find this on letters you've received from The Christie.
      </div>

      <h5 className="mb-2">Please enter your NHS number:</h5>

      <div className="mb-3">
        <Input type="text" onChange={val => setNhs(val)} disabled={props.disable} />
      </div>

      <Button label="Submit" fullWidth disabled={!nhs || props.disable} onClick={() => nhs && props.onSubmit(nhs)} />
    </>
  );
}
