// ClientApp-angular/src/app/pages/login/components/number-select/number-select.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-number-select',
  templateUrl: './number-select.component.html',
  styleUrls: ['./number-select.component.scss']
})
export class NumberSelectComponent implements OnInit {

  constructor() { }

  @Input() numbers: string[] = [];
  @Input() disable: boolean = false;

  @Output() submit: EventEmitter<string> = new EventEmitter();

  canSendCode: boolean = false;

  private selectedNumber: string = '';

  ngOnInit(): void {
    this.numbers.sort(() => 0.5 - Math.random());
  }

  onPhoneSelected(number: string) {
    this.selectedNumber = number;
    this.canSendCode = true;
  }

  onSendCode() {
    this.submit.emit(this.selectedNumber);
  }
}

<div class="text mb-4">
  To complete the login process we need to send a verification code to your mobile phone.
</div>

<h6 class="limit-width mb-2">Please select your phone number:</h6>

<div class="limit-width mb-3">
  <div *ngFor="let n of numbers; let i = index" class="number-option">
    <input type="radio" class="btn-check" name="phone-number-group" id="phone-number-radio-{{i}}" autocomplete="off"
      (change)="onPhoneSelected(n)" [disabled]="disable">
    <label class="btn btn-outline-dark w-100" for="phone-number-radio-{{i}}">{{n}}</label>
  </div>
</div>

<div class="limit-width">
  <button class="btn btn-primary w-100" [disabled]="!canSendCode || disable" (click)="onSendCode()">
    Send verification code
  </button>
</div>

// ClientApp/src/pages/Login/PromsLogin/components/NumberSelect.tsx
import React from "react";
import { Button } from "src/components/atoms/Button/Button";
import { OptionButton } from "src/components/molecules/OptionButton/OptionButton";

interface IProps {
  numbers: string[];
  disable?: boolean;
  onSelectNumber: (number: string) => void;
}

export const NumberSelect: React.FC<IProps> = (props): JSX.Element => {
  const [selected, setSelected] = React.useState<string>();

  return (
    <>
      <div className="mb-4">
        To complete the login process we need to send a verification code to your mobile phone.
      </div>

      <h6 className="mb-2">Please select your phone number:</h6>

      <div className="mb-3">
        {
          props.numbers.map((x, i) => (

            <OptionButton
              key={i}
              label={x}
              name="phone-number-group"
              disabled={props.disable}
              onChange={val => setSelected(val)}
            />

          ))
        }
      </div>

      <Button
        label="Send verification code"
        fullWidth
        disabled={!selected || props.disable}
        onClick={() => selected && props.onSelectNumber(selected)}
      />
    </>
  );
}
