// ClientApp-angular/src/app/pages/login/components/one-time/one-time.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-one-time',
  templateUrl: './one-time.component.html',
  styleUrls: ['./one-time.component.scss']
})
export class OneTimeComponent implements OnInit {

  constructor() { }

  @Input() disable: boolean = false;
  @Input() viaSms: boolean = true;

  @Output() submit: EventEmitter<string> = new EventEmitter();
  @Output() tryAgain: EventEmitter<any> = new EventEmitter();

  code: string = '';
  instruction: string = '';

  ngOnInit(): void {
    this.instruction = this.viaSms
      ? 'to your mobile device'
      : 'to your registered email address'
  }

  onSubmit() {
    this.submit.emit(this.code);
  }

  onTryAgain(): void {
    this.tryAgain.emit();
  }
}

<div class="text mb-4">
  To complete the login process please enter the 6-digit verification code sent {{instruction}}.
</div>

<h5 class="limit-width mb-2">Please enter the 6-digit code:</h5>

<div class="limit-width mb-3">
  <input type="text" class="form-control" maxlength="6" [(ngModel)]="code" [disabled]="disable">
</div>

<div class="limit-width mb-5">
  <button class="btn btn-primary w-100" [disabled]="!(code && code.length === 6) || disable" (click)="onSubmit()">
    Submit
  </button>
</div>

<div class="limit-width d-flex-col-center">

  <h6>Didn't receive a code?</h6>
  <div class="text">
    Click the link below to try signing in again
  </div>

  <div>
    <button class="btn btn-link w-100" (click)="onTryAgain()">
      Sign in again
    </button>
  </div>

</div>

// ClientApp/src/pages/Login/PromsLogin/components/OneTime.tsx
import React from "react";
import { Button } from "src/components/atoms/Button/Button";
import { Flex } from "src/components/atoms/Flex";
import { Input } from "src/components/atoms/Input";

interface IProps {
  viaSms: boolean;
  disable?: boolean;
  onSubmit: (code: string) => void;
  onTryAgain: () => void;
}

export const OneTime: React.FC<IProps> = (props): JSX.Element => {
  const [code, setCode] = React.useState<string>();

  const instruction = props.viaSms
    ? 'to your mobile device'
    : 'to your registered email address';

  return (
    <>
      <div className="mb-4">
        To complete the login process please enter the 6-digit verification code sent {instruction}.
      </div>

      <h5 className="mb-2">Please enter the 6-digit code:</h5>

      <div className="mb-3">
        <Input type="text" maxLength={6} disabled={props.disable} onChange={val => setCode(val)} />
      </div>

      <div className="mb-5">
        <Button
          label="Submit"
          fullWidth
          disabled={!(code && code.length === 6) || props.disable}
          onClick={() => code && code.length === 6 && props.onSubmit(code)}
        />
      </div>

      <Flex col alignItems="center">
        <h6>Didn't receive a code?</h6>
        <div>
          Click the link below to try signing in again
        </div>
        <Button label="Sign in again" fullWidth variant="link" onClick={props.onTryAgain} />
      </Flex>
    </>
  );
}
