// ClientApp/src/pages/Forms/FormsRequest/components/FormRequestExpired.tsx
import { useNavigate } from "react-router-dom";
import { AppRoutes } from "src/AppRoutes";
import { Button } from "src/components/atoms/Button/Button";
import { Flex } from "src/components/atoms/Flex";

interface IProps { }

export const FormRequestExpired: React.FC<IProps> = (props): JSX.Element => {
  const nav = useNavigate();

  return (
    <>
      <h3>Link Expired.</h3>

      <div className="mb-3">
        Sorry, the link you've used has expired.
      </div>

      <div className="mb-3">
        You can use the links below to view forms you have completed previously, or go back to your home page.
      </div>

      <Flex>
        <Button label="Home page" fullWidth className="me-3" onClick={() => nav(AppRoutes.home)} />
        <Button label="My Forms" fullWidth onClick={() => nav(AppRoutes.forms)} />
      </Flex>
    </>
  );
}

// ClientApp-angular/src/app/pages/main-layout/pages/form-request/components/form-request-expired/form-request-expired.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-form-request-expired',
  templateUrl: './form-request-expired.component.html',
  styleUrls: ['./form-request-expired.component.scss']
})
export class FormRequestExpiredComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h3>Link Expired.</h3>

<div class="text">
  Sorry, the link you've used has expired.
</div>

<div class="text">
  You can use the links below to view forms you have completed previously, or go back to your home page.
</div>

<div class="d-flex">
  <a class="btn btn-primary w-100 me-3" routerLink="/">
    Home page
  </a>
  <a class="btn btn-primary w-100" routerLink="/forms">
    My Forms
  </a>
</div>
