// ClientApp-angular/src/app/pages/main-layout/pages/form-request/components/form-request-options/form-request-options.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-form-request-options',
  templateUrl: './form-request-options.component.html',
  styleUrls: ['./form-request-options.component.scss']
})
export class FormRequestOptionsComponent implements OnInit {
  constructor(private router: Router) { }

  @Input() formName: string = '';

  @Output() continue: EventEmitter<any> = new EventEmitter();
  @Output() later: EventEmitter<any> = new EventEmitter();
  @Output() decline: EventEmitter<any> = new EventEmitter();

  ngOnInit(): void { }

  onContinue(): void {
    this.continue.emit();
  }

  onLater(): void {
    this.later.emit();
  }

  onDecline(): void {
    this.decline.emit();
  }
}

<h3>New questionnaire</h3>

<div class="text">
  You have been asked to complete a questionnaire.
</div>

<div class="text">
  Please click <strong>Continue</strong> to complete it.
</div>

<div>
  <button class="btn btn-primary w-100 mb-3" (click)="onContinue()">
    Continue
  </button>
  <button class="btn btn-link w-100" (click)="onLater()">
    I'll complete this later
  </button>
  <button class="btn btn-link w-100" (click)="onDecline()">
    I don't want to complete this questionnaire
  </button>
</div>

// ClientApp/src/pages/Forms/FormsRequest/components/FormRequestOptions.tsx
import { Button } from "src/components/atoms/Button/Button";

interface IProps {
  onContinue: () => void;
  onLater: () => void;
  onDecline: () => void;
}

export const FormRequestOptions: React.FC<IProps> = (props): JSX.Element => {

  return (
    <>
      <h3>New questionnaire</h3>

      <div className="mb-3">
        You have been asked to complete a questionnaire.
      </div>

      <div className="mb-3">
        Please click <strong>Continue</strong> to complete it.
      </div>

      <div>
        <Button label="Continue" fullWidth className="mb-3" onClick={props.onContinue} />
        <Button label="I'll complete this later" variant="link" fullWidth onClick={props.onLater} />
        <Button label="I don't want to complete this questionnaire" variant="link" fullWidth onClick={props.onDecline} />
      </div>

    </>
  );
}
