// ClientApp/src/pages/Forms/FormsRequestFeedback/FormRequestFeedback.tsx
import { useNavigate } from "react-router-dom";
import { AppRoutes } from "src/AppRoutes";
import { Button } from "src/components/atoms/Button/Button";
import { Flex } from "src/components/atoms/Flex";
import { LimitWidthContainer } from "src/components/layouts/LimitWidthContainer";

interface IProps { }

export const FormRequestFeedback: React.FC<IProps> = (props): JSX.Element => {
  const nav = useNavigate();

  return (
    <LimitWidthContainer>

      <h3>Thank you.</h3>

      <div className="mb-3">
        Thanks for your feedback.
      </div>

      <div className="mb-3">
        You can use the links below to view forms you have completed previously, or go back to your home page.
      </div>

      <Flex>
        <Button label="Home page" fullWidth className="me-3" onClick={() => nav(AppRoutes.home)} />
        <Button label="My Forms" fullWidth onClick={() => nav(AppRoutes.forms)} />
      </Flex>

    </LimitWidthContainer>
  );
}

// ClientApp-angular/src/app/pages/main-layout/pages/form-request/components/form-request-feedback/form-request-feedback.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-form-request-feedback',
  templateUrl: './form-request-feedback.component.html',
  styleUrls: ['./form-request-feedback.component.scss']
})
export class FormRequestFeedbackComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h3>Thank you.</h3>

<div class="text">
  Thanks for your feedback.
</div>

<div class="text">
  You can use the links below to view forms you have completed previously, or go back to your home page.
</div>

<div class="d-flex">
  <a class="btn btn-primary w-100 me-3" routerLink="/">
    Home page
  </a>
  <a class="btn btn-primary w-100" routerLink="/forms">
    My Forms
  </a>
</div>
